<?php
return array (
  'widget_pos.category_view_sidebar' => 'Просмотр категории: Боковая панель',
  'widget_pos.conversation_list_sidebar' => 'Список переписок: Боковая панель',
  'widget_pos.conversation_view_sidebar' => 'Просмотр переписки: Боковая панель',
  'widget_pos.find_threads_sidenav' => 'Поиск тем: боковая навигация',
  'widget_pos.forum_list_above_nodes' => 'Список разделов: Над узлами',
  'widget_pos.forum_list_below_nodes' => 'Список разделов: Под узлами',
  'widget_pos.forum_list_sidebar' => 'Список разделов: Боковая панель',
  'widget_pos.forum_new_posts_sidebar' => 'Новые сообщения: боковая навигация',
  'widget_pos.forum_overview_bottom' => 'Список разделов: внизу',
  'widget_pos.forum_overview_top' => 'Список разделов: сверху',
  'widget_pos.forum_view_sidebar' => 'Просмотр раздела: боковая панель',
  'widget_pos.help_page_sidenav' => 'Страница помощи: Боковая навигация',
  'widget_pos.member_view_sidebar' => 'Профиль пользователя: Боковая панель',
  'widget_pos.member_wrapper_sidenav' => 'Профиль пользователя: боковая навигация',
  'widget_pos.online_list_sidebar' => 'Список онлайн: Боковая панель',
  'widget_pos.pub_sidebar_bottom' => 'На всех страницах: Внизу боковой панели',
  'widget_pos.pub_sidebar_top' => 'На всех страницах: Вверху боковой панели',
  'widget_pos.th_footer_uix' => 'UI.X: Extended footer',
  'widget_pos.th_sidebarNavigation_uix' => 'UI.X: Sidebar navigation',
  'widget_pos.thread_view_above_messages' => 'Просмотр темы: выше сообщений',
  'widget_pos.thread_view_below_messages' => 'Просмотр темы: ниже сообщений',
  'widget_pos.thread_view_below_quick_reply' => 'Просмотр темы: ниже быстрого ответа',
  'widget_pos.thread_view_sidebar' => 'Просмотр темы: Боковая панель',
  'widget_pos.thuix_index_page' => 'Forums default page: Sidebar',
  'widget_pos.whats_new_overview' => 'Что нового: Обзор',
  'widget_pos.whats_new_sidenav' => 'Что нового: Боковая навигация',
);